# .travis.yml

dist: trusty
sudo: false
language: node_js
node_js:
    - 6.11.1

addons:
  chrome: stable

services:
    - mysql

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm i -g npm@5.3.0
    - mysql -u root --password="" < patientPortalDB.sql

install:
    # Install Frontend Dependencies
    - cd client
    - npm install
    - npm rebuild
    - ng build
    # Install Backend Dependencies
    - cd ..
    - cd server
    - npm install
    - npm rebuild
    - cd ..

script:
    # Frontend build
    - cd client
    - npm run ci
    - cd ..
    # Backend build
    - cd server
    - npm run intTest -s && npm run unitTest -s
