# .travis.yml

dist: trusty
sudo: false
language: node_js
node_js:
    - 6.11.1

addons:
apt:
    sources:
        - google-chrome
    packages:
        - google-chrome-stable

services:
    - mysql

before_install:
    # Set npm version to 5.3.0
    - npm i -g npm@5.3.0
    # Run db script file to create and populate database
    - mysql -u root --password="" < patientPortalDB.sql
    - webdriver-manager clean webdriver-manager update --versions.chrome 2.30 
install:
    # Install Frontend Dependencies
    - cd client
    - npm install
    - ng build
    # Install Backend Dependencies
    - cd ..
    - cd server
    - npm install
    - cd ..

script:
    # Frontend build
    - cd client
    - npm run ci
    - cd ..
    # Backend build
    - cd server
    - npm run intTest -s && npm run unitTest -s
