# .travis.yml

dist: trusty
sudo: false
language: node_js
node_js:
    - 8.9.1

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

services:
    - mysql

before_install:
    # Set npm version to 5.3.0
    - npm i -g npm@5.5.1
    # Run db script file to create and populate database
    - mysql -u root --password="" < patientPortalDB.sql

install:
    # Install Frontend Dependencies
    - cd client
    - npm install
    - ng build
    # Install Backend Dependencies
    - cd ..
    - cd server
    - npm install
    - cd ..

script:
    # Frontend build
    - cd client
    - ng test --single-run
    - cd ..
    # Backend build
    - cd server
    - npm run intTest -s && npm run unitTest -s
