# .travis.yml

dist: trusty
sudo: false
language: node_js
node_js:
    - 6.11.1

addons:
  chrome: stable

services:
    - mysql

before_install:
    # Set npm version to 5.3.0
    - npm i -g npm@5.3.0
    # Run db script file to create and populate database
    - mysql -u root --password="" < patientPortalDB.sql

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

install:
    # Install Frontend Dependencies
    - cd client
    - npm install
    - npm rebuild
    - ng build
    # Install Backend Dependencies
    - cd ..
    - cd server
    - npm install
    - npm rebuild
    - cd ..

script:
    # Frontend build
    - cd client
    - npm run ci
    - cd ..
    # Backend build
    - cd server
    - npm run intTest -s && npm run unitTest -s
